### PR TITLE
Fixing eslint errors, removed unused imports and fixed console error …

### LINKED ISSUE #82: fix lint and console errors
eslint errors for:
- OperatorClientMenu.jsx
- index.js

console error regarding:
- repeat attribute does not exist for animate tag

### PR DESCRIPTION
**Pull request by broneks**
…regarding an invalid svg attribute

close #82

### CODE REVIEW

File: src/components/MessageList/MessageList.jsx [hunk 1]
```diff
@@ -74,7 +74,7 @@ class MessageList extends Component {
                 to="16"
                 values="16; 12; 16;"
                 dur="500ms"
-                repeat="always"
+                restart="always"
```
Comment (mihok) [inline src/components/MessageList/MessageList.jsx]: Was that ALL that we had to do to get that warning to go away? does it still restart! This is amaze!
